language: bash
services: docker

script:
  - cd docker && ./makeDockerfiles.sh

after_script:
  - docker images

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - build/cache

before_install:
 - nvm install 7
 - nvm use 7

install:
  - npm install
  - ./node_modules/gulp/bin/gulp.js init

before_script:
  - mysql -e "create database IF NOT EXISTS omeka_test;" -uroot
  - sed -i 's/^host.*/host = "localhost"/' application/test/config/database.ini
  - sed -i 's/^user.*/user = "root"/' application/test/config/database.ini
  - sed -i 's/^dbname.*/dbname = "omeka_test"/' application/test/config/database.ini

script: ./node_modules/gulp/bin/gulp.js test --continue
